### ISSUE TITLE
Deserialising rabbitMQ messages fails when I switch to batch execution using celery-batches

### ISSUE THREAD

**Issue by philippfreyer** [percipient/celery-batches#9]
### Problem description
I had an update task that I created in celery that aggregates long-running document update requests together in Postgres and executes them in batches. Since this was not optimal (huge amount of work to update aggregated lists in the database), I was trying to use celery-batches to retrieve and process the single tasks in batches and thus have fewer database updates.
As soon as I switch to celery-batches, I have decoder errors when trying to continue work on the old queue (I figured, that this should be possible since celery-batches seemed to only aggregate the previous requests - is that right?)

However, when I check the logfiles of my celery worker, I see errors when deserialising the rabbitMQ messages. Those messages deserialized just fine when I was in single-processing mode.

Anything that I am doing wrong or is this an issue in celery-batches? I am happy to debug myself and create a patch, but I would like to first confirm that what I am doing is correct and that I am using celery-batches as intended.

### Example data
**celery message (taken from RabbitMQ Management**
![image](https://user-images.githubusercontent.com/29856235/46346641-f7139200-c648-11e8-8b17-268c35834f28.png)

**Task**
```
@shared_task(
    base=Batches,
    flush_every=1000,
    flush_interval=10,
    bind=False,
    queue='did_update_aggregation',
    routing_key='omg.did_update_aggregation',
    max_retries=5)
def aggregate_did_task(requests):
    aggregate_by_scenario_id = {}
    for request in requests:
        scenario_id = request.args[0]
        did = request.args[1]
        if scenario_id not in aggregate_by_scenario_id:
            aggregate_by_scenario_id[scenario_id] = [did]
        else:
            aggregate_by_scenario_id[scenario_id].append(did)
    for scenario_id, did_list in aggregate_by_scenario_id.iteritems():
        aggregate_dids(scenario_id=scenario_id, did_list=did_list)
```

**previous implementation**
```
@shared_task(
    base=Task,
    bind=False,
    queue='did_update_aggregation',
    routing_key='omg.did_update_aggregation',
    max_retries=5)
def aggregate_did_task(scenario_id, did, **_kwargs):
    aggregate_did(scenario_id=scenario_id, did=did)
```

**Async call**
`aggregate_did_task.apply_async(args=(scenario_id, did,))`

**Stacktrace in log**
```
  File "/usr/local/lib/python2.7/site-packages/vine/promises.py", line 140, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python2.7/site-packages/librabbitmq/__init__.py", line 227, in drain_events
    self._basic_recv(timeout)
  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 567, in on_task_received
    callbacks,
  File "/usr/local/lib/python2.7/site-packages/celery_batches/__init__.py", line 254, in task_message_handler
    flush_buffer()
  File "/usr/local/lib/python2.7/site-packages/celery_batches/__init__.py", line 269, in _do_flush
    self.flush(requests)
  File "/usr/local/lib/python2.7/site-packages/celery_batches/__init__.py", line 260, in flush
    for r in requests],))
  File "/usr/local/lib/python2.7/site-packages/celery_batches/__init__.py", line 195, in from_request
    args, kwargs, embed = request._payload
  File "/usr/local/lib/python2.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/request.py", line 478, in _payload
    return self.body if self._decoded else self.message.payload
  File "/usr/local/lib/python2.7/site-packages/kombu/message.py", line 207, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/usr/local/lib/python2.7/site-packages/kombu/message.py", line 192, in decode
    self._decoded_cache = self._decode()
  File "/usr/local/lib/python2.7/site-packages/kombu/message.py", line 197, in _decode
    self.content_encoding, accept=self.accept)
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python2.7/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/local/lib/python2.7/site-packages/bson/json_util.py", line 438, in loads
    return json.loads(s, *args, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
DecodeError: expected string or buffer
```

**Comment by clokep** [comment]
I haven't tried switching an implementation on the fly from individual task runs to a batch task run. I also have run celery-batches using a shared task, but I'd be surprised if that caused the issue.

To switch from a non-batches to a batches version of a task I usually create a second task that has a similar implementation and then start calling the new task. E.g.
1. Add `aggregate_did_task_batch` task
2. Start calling `aggregate_did_task_batch.apply_async`
3. Wait for all the queued `aggregate_did_task` task calls to be processed
4. Remove `aggregate_did_task`

You can essentially go through the same steps if you would want to rename a task, but that's optional.

What version of celery and kombu are you using? What task protocol version are you using?

**Comment by philippfreyer** [comment]
Great news - I was just jumping to conclusions too fast :-)

In my effort to speed up processing as much as possible I added celery-batch and I also introduced librabbitmq into the deployment in order to speed up the Celery RabbitMQ interface. I noticed that my (unrelated) tasks still threw the same exceptions after I removed my batch processing code again.

The only common component between the stack trace above and the new ones was librabbitmq. After I removed that one again, the error disappeared and celery-batch (which I then reintroduced again) worked completely fine with the already existing tasks. The backlog of 44.000 messages was reduced to 0 within 30 seconds - a process that took hours before.

Thus, this issue does not have anything to do with celery-batch.

That also means that - while I really like your alternative procedure to replace a task when I would change the interface - a drop-in replacement works as long as the method signature is not being changed - great news IMHO.

Regarding celery and kombu (just for completeness):
Celery version 4.2.1
Kombu is as well 4.2.1
Task protocol is not set anywhere, so it should be the default - v2

**Comment by clokep** [comment]
Awesome news! 👍 Thanks for getting back to me on this! (Also -- awesome to hear how much this reduced your processing time. Success stories are great! 💥 )

I *think* this means this issue can be closed then. Please let me know if there's anything left to do here!

**Comment by philippfreyer** [comment]
Thanks, closing the issue is fine - thank you for replying so fast - this was really helpful and caused me to look deeper into the issue, even if it was somewhere else in the end :-)

**Comment by clokep** [comment]
No problem! Please let me know if you see any other issues while using celery-batches!
